### ISSUE TITLE
documentation update for hyper-v support

### ISSUE THREAD

**Issue by Sandalorian** [sirReeall/vagrant_machines#15]
From the work done in #4 we need to document an issue with hyper-v switches:

```
    dc01: Please choose a switch to attach to your Hyper-V instance.
    dc01: If none of these are appropriate, please open the Hyper-V manager
    dc01: to create a new virtual switch.
    dc01:
    dc01: 1) New Virtual Switch
    dc01: 2) Default Switch
    dc01:
    dc01: What switch would you like to use? 1
```
In this case, the switch that is select needs to be accessible from the host machine where vagrant is running from

If user is not sure, then select the default switch
